// Auto-generated by gen_g4.py -- do not edit by hand.
// Logo data source: cucei_r.json
// Target physical width: 80.0 mm, height: 113.15 mm
#include "LogoGeometryData.hh"
#include "G4SystemOfUnits.hh"
#include <vector>

std::vector<LogoGroup> BuildCUCEI_R_LogoData()
{
  // source image: 794x1123 px, scale = 0.100756 mm/px, target width = 80.0 mm (height = 113.15 mm)
  std::vector<LogoGroup> groups;

  { // group: navy_R
    LogoGroup grp;
    grp.name = "navy_R";
    grp.colour = G4Colour(0.0000, 0.0000, 0.4392);
    grp.shapes.reserve(2);
    {
      LogoPolygon poly;
      poly.outer = { G4TwoVector(5.8438*mm, 51.5365*mm), G4TwoVector(-0.2015*mm, 36.4232*mm), G4TwoVector(2.7204*mm, 33.8035*mm), G4TwoVector(5.3401*mm, 30.2771*mm), G4TwoVector(6.9521*mm, 26.2469*mm), G4TwoVector(7.1537*mm, 21.9144*mm), G4TwoVector(6.4484*mm, 19.3955*mm), G4TwoVector(4.9370*mm, 16.6751*mm), G4TwoVector(2.4181*mm, 13.9547*mm), G4TwoVector(0.2015*mm, 12.3426*mm), G4TwoVector(16.1209*mm, -18.5894*mm), G4TwoVector(27.7078*mm, -18.5894*mm), G4TwoVector(8.9673*mm, 6.8010*mm), G4TwoVector(14.2065*mm, 12.0403*mm), G4TwoVector(18.2368*mm, 17.8841*mm), G4TwoVector(20.5542*mm, 23.7280*mm), G4TwoVector(20.9572*mm, 29.2695*mm), G4TwoVector(19.4458*mm, 36.1209*mm), G4TwoVector(16.2217*mm, 42.4685*mm), G4TwoVector(11.3854*mm, 47.8086*mm) };
      grp.shapes.push_back(poly);
    }
    {
      LogoPolygon poly;
      poly.outer = { G4TwoVector(-13.1990*mm, 55.3652*mm), G4TwoVector(-20.9572*mm, 54.4584*mm), G4TwoVector(-26.3980*mm, 52.5441*mm), G4TwoVector(-19.7481*mm, 34.4081*mm), G4TwoVector(-24.4836*mm, 31.9899*mm), G4TwoVector(-28.4131*mm, 28.8665*mm), G4TwoVector(-31.0327*mm, 25.4408*mm), G4TwoVector(-32.6448*mm, 20.9068*mm), G4TwoVector(-32.7456*mm, 17.5819*mm), G4TwoVector(-32.1411*mm, 14.1562*mm), G4TwoVector(-29.7229*mm, 9.3199*mm), G4TwoVector(-25.4912*mm, 5.1889*mm), G4TwoVector(-18.4383*mm, 1.6625*mm), G4TwoVector(-24.3829*mm, -18.5894*mm), G4TwoVector(-10.4786*mm, -18.5894*mm), G4TwoVector(-10.4786*mm, 3.8791*mm), G4TwoVector(-16.1209*mm, 4.9874*mm), G4TwoVector(-20.5542*mm, 7.6071*mm), G4TwoVector(-23.4761*mm, 11.5365*mm), G4TwoVector(-24.5844*mm, 15.8690*mm), G4TwoVector(-24.2821*mm, 20.1008*mm), G4TwoVector(-22.3678*mm, 23.9295*mm), G4TwoVector(-19.2443*mm, 26.9521*mm), G4TwoVector(-13.5013*mm, 29.9748*mm) };
      grp.shapes.push_back(poly);
    }
    groups.push_back(grp);
  }

  { // group: orange_R
    LogoGroup grp;
    grp.name = "orange_R";
    grp.colour = G4Colour(1.0000, 0.4000, 0.0000);
    grp.shapes.reserve(1);
    {
      LogoPolygon poly;
      poly.outer = { G4TwoVector(-10.4786*mm, 55.6675*mm), G4TwoVector(-10.4786*mm, 27.7582*mm), G4TwoVector(-15.6171*mm, 25.7431*mm), G4TwoVector(-19.2443*mm, 22.8212*mm), G4TwoVector(-21.0579*mm, 19.0932*mm), G4TwoVector(-20.9572*mm, 14.7607*mm), G4TwoVector(-19.6474*mm, 11.9395*mm), G4TwoVector(-17.0277*mm, 9.6222*mm), G4TwoVector(-12.6952*mm, 8.0101*mm), G4TwoVector(-7.1537*mm, 7.5063*mm), G4TwoVector(-7.2544*mm, -18.5894*mm), G4TwoVector(12.1914*mm, -18.5894*mm), G4TwoVector(-3.4257*mm, 12.1411*mm), G4TwoVector(-0.6045*mm, 14.5592*mm), G4TwoVector(1.4106*mm, 17.1788*mm), G4TwoVector(3.3249*mm, 22.3174*mm), G4TwoVector(3.3249*mm, 25.8438*mm), G4TwoVector(2.2166*mm, 29.0680*mm), G4TwoVector(0.4030*mm, 31.6877*mm), G4TwoVector(-3.8287*mm, 35.3149*mm), G4TwoVector(2.1159*mm, 53.2494*mm), G4TwoVector(-4.5340*mm, 55.2645*mm) };
      grp.shapes.push_back(poly);
    }
    groups.push_back(grp);
  }

  { // group: black_text
    LogoGroup grp;
    grp.name = "black_text";
    grp.colour = G4Colour(0.0000, 0.0000, 0.0000);
    grp.shapes.reserve(5);
    {
      LogoPolygon poly;
      poly.outer = { G4TwoVector(24.3829*mm, -21.7128*mm), G4TwoVector(24.3829*mm, -48.3123*mm), G4TwoVector(27.8086*mm, -48.3123*mm), G4TwoVector(27.8086*mm, -21.8136*mm), G4TwoVector(27.7078*mm, -21.7128*mm) };
      grp.shapes.push_back(poly);
    }
    {
      LogoPolygon poly;
      poly.outer = { G4TwoVector(10.4786*mm, -21.7128*mm), G4TwoVector(10.4786*mm, -41.1587*mm), G4TwoVector(6.0453*mm, -41.2594*mm), G4TwoVector(7.7582*mm, -43.1738*mm), G4TwoVector(10.4786*mm, -43.2746*mm), G4TwoVector(10.5793*mm, -46.5995*mm), G4TwoVector(11.4861*mm, -47.7078*mm), G4TwoVector(12.9975*mm, -48.3123*mm), G4TwoVector(20.9572*mm, -48.3123*mm), G4TwoVector(20.9572*mm, -45.9950*mm), G4TwoVector(16.2217*mm, -45.6927*mm), G4TwoVector(14.9118*mm, -45.0882*mm), G4TwoVector(14.2065*mm, -43.8791*mm), G4TwoVector(14.3073*mm, -43.1738*mm), G4TwoVector(20.9572*mm, -43.1738*mm), G4TwoVector(20.9572*mm, -41.2594*mm), G4TwoVector(14.2065*mm, -41.1587*mm), G4TwoVector(14.2065*mm, -25.0378*mm), G4TwoVector(20.9572*mm, -24.9370*mm), G4TwoVector(20.9572*mm, -21.7128*mm) };
      grp.shapes.push_back(poly);
    }
    {
      LogoPolygon poly;
      poly.outer = { G4TwoVector(2.0151*mm, -21.7128*mm), G4TwoVector(-0.5038*mm, -24.5340*mm), G4TwoVector(-1.9144*mm, -26.7506*mm), G4TwoVector(-3.1234*mm, -29.2695*mm), G4TwoVector(-3.9295*mm, -31.8892*mm), G4TwoVector(-4.2317*mm, -33.8035*mm), G4TwoVector(-4.1310*mm, -37.6322*mm), G4TwoVector(-3.6272*mm, -39.8489*mm), G4TwoVector(-2.9219*mm, -41.7632*mm), G4TwoVector(-1.5113*mm, -44.3829*mm), G4TwoVector(0.5038*mm, -47.1033*mm), G4TwoVector(1.7128*mm, -48.3123*mm), G4TwoVector(6.0453*mm, -48.3123*mm), G4TwoVector(3.7280*mm, -46.1965*mm), G4TwoVector(1.8136*mm, -43.7783*mm), G4TwoVector(0.1008*mm, -40.5542*mm), G4TwoVector(-0.7053*mm, -37.8338*mm), G4TwoVector(-0.9068*mm, -36.2217*mm), G4TwoVector(-0.8060*mm, -33.6020*mm), G4TwoVector(-0.3023*mm, -31.3854*mm), G4TwoVector(0.3023*mm, -29.7733*mm), G4TwoVector(1.6121*mm, -27.3552*mm), G4TwoVector(2.8212*mm, -25.6423*mm), G4TwoVector(6.5491*mm, -21.7128*mm) };
      grp.shapes.push_back(poly);
    }
    {
      LogoPolygon poly;
      poly.outer = { G4TwoVector(-18.4383*mm, -21.7128*mm), G4TwoVector(-18.4383*mm, -45.3904*mm), G4TwoVector(-17.5315*mm, -46.8010*mm), G4TwoVector(-15.2141*mm, -48.0101*mm), G4TwoVector(-13.8035*mm, -48.3123*mm), G4TwoVector(-11.5869*mm, -48.3123*mm), G4TwoVector(-10.2771*mm, -48.0101*mm), G4TwoVector(-8.2620*mm, -46.9018*mm), G4TwoVector(-7.6574*mm, -46.1965*mm), G4TwoVector(-7.2544*mm, -44.9874*mm), G4TwoVector(-7.3552*mm, -21.7128*mm), G4TwoVector(-10.2771*mm, -21.7128*mm), G4TwoVector(-10.2771*mm, -44.3829*mm), G4TwoVector(-10.5793*mm, -45.1889*mm), G4TwoVector(-11.7884*mm, -45.8942*mm), G4TwoVector(-14.3073*mm, -45.6927*mm), G4TwoVector(-15.2141*mm, -44.4836*mm), G4TwoVector(-15.2141*mm, -21.8136*mm) };
      grp.shapes.push_back(poly);
    }
    {
      LogoPolygon poly;
      poly.outer = { G4TwoVector(-26.5995*mm, -21.7128*mm), G4TwoVector(-29.2191*mm, -24.7355*mm), G4TwoVector(-30.8312*mm, -27.3552*mm), G4TwoVector(-31.7380*mm, -29.3703*mm), G4TwoVector(-32.2418*mm, -30.8816*mm), G4TwoVector(-32.7456*mm, -33.2997*mm), G4TwoVector(-32.8463*mm, -35.9194*mm), G4TwoVector(-32.6448*mm, -37.8338*mm), G4TwoVector(-31.8388*mm, -40.8564*mm), G4TwoVector(-30.7305*mm, -43.2746*mm), G4TwoVector(-29.5214*mm, -45.1889*mm), G4TwoVector(-27.7078*mm, -47.5063*mm), G4TwoVector(-26.9018*mm, -48.3123*mm), G4TwoVector(-22.5693*mm, -48.3123*mm), G4TwoVector(-25.2897*mm, -45.6927*mm), G4TwoVector(-27.2040*mm, -43.0730*mm), G4TwoVector(-28.6146*mm, -40.1511*mm), G4TwoVector(-29.3199*mm, -37.5315*mm), G4TwoVector(-29.4207*mm, -33.9043*mm), G4TwoVector(-28.9169*mm, -31.4861*mm), G4TwoVector(-28.3123*mm, -29.8741*mm), G4TwoVector(-27.1033*mm, -27.5567*mm), G4TwoVector(-25.6927*mm, -25.5416*mm), G4TwoVector(-24.6851*mm, -24.3325*mm), G4TwoVector(-22.0655*mm, -21.8136*mm) };
      grp.shapes.push_back(poly);
    }
    groups.push_back(grp);
  }

  return groups;
}
