// Auto-generated by gen_g4.py -- do not edit by hand.
#include "../include/LogoGeometryBuilder.hh"

#include "G4ExtrudedSolid.hh"
#include "G4SubtractionSolid.hh"
#include "G4VSolid.hh"
#include "G4Material.hh"
#include "G4LogicalVolume.hh"
#include "G4PVPlacement.hh"
#include "G4VisAttributes.hh"
#include "G4SystemOfUnits.hh"
#include <string>

int BuildLogoGeometry(const std::vector<LogoGroup>& groups,
                      G4double halfThicknessMm,
                      G4Material* material,
                      G4LogicalVolume* motherLV,
                      const G4ThreeVector& position,
                      G4bool checkOverlaps,
                      G4int copyNoStart,
                      G4double scale)
{
  const G4double halfZ = halfThicknessMm * mm;
  const G4double holeHalfZ = halfZ + 0.5 * mm; // slightly thicker so the
                                                // subtraction cleanly cuts
                                                // all the way through
  const G4TwoVector zero(0., 0.);

  G4int copyNo = copyNoStart;
  G4int shapeCount = 0;

  for (const auto& grp : groups) {
    auto* vis = new G4VisAttributes(grp.colour);
    vis->SetForceSolid(true);

    G4int shapeIdx = 0;
    for (const auto& poly : grp.shapes) {
      if (poly.outer.size() < 3) continue;

      G4String baseName = grp.name + "_" + std::to_string(shapeIdx);

      // scale1 == scale2 == 'scale' at both end-caps (offset 'zero' at
      // both) gives a straight (non-tapered) prism, uniformly resized
      // about the polygon's own local origin -- i.e. exactly a smaller/
      // larger copy of the same shape, not a taper.
      G4VSolid* solid = new G4ExtrudedSolid(baseName, poly.outer, halfZ,
                                             zero, scale, zero, scale);

      G4int holeIdx = 0;
      for (const auto& hole : poly.holes) {
        if (hole.size() < 3) { ++holeIdx; continue; }
        G4String holeName = baseName + "_hole" + std::to_string(holeIdx);
        // Same 'scale' as the outer polygon (and the SAME local origin,
        // 'zero'): holes must be scaled identically to stay aligned with
        // the (now smaller/larger) outer boundary they cut out of.
        auto* holeSolid = new G4ExtrudedSolid(holeName, hole, holeHalfZ,
                                               zero, scale, zero, scale);
        solid = new G4SubtractionSolid(baseName + "_cut" + std::to_string(holeIdx),
                                        solid, holeSolid);
        ++holeIdx;
      }

      auto* lv = new G4LogicalVolume(solid, material, baseName + "_LV");
      lv->SetVisAttributes(vis);

      new G4PVPlacement(nullptr, position, lv, baseName + "_PV", motherLV,
                         false, copyNo, checkOverlaps);
      ++copyNo;
      ++shapeIdx;
      ++shapeCount;
    }
  }

  return shapeCount;
}
