// Auto-generated by gen_g4.py -- do not edit by hand.
#ifndef CUCEI_R_LogoData_hh
#define CUCEI_R_LogoData_hh

#include "LogoGeometryData.hh"
#include <vector>

// Physical footprint: 80.0 mm wide x 113.15 mm tall, centred on
// the image's own centre (local origin = geometric centre of the logo).
std::vector<LogoGroup> BuildCUCEI_R_LogoData();

#endif
