// Auto-generated by gen_g4.py -- do not edit by hand.
#ifndef CUCEIBannerLogoData_hh
#define CUCEIBannerLogoData_hh

#include "LogoGeometryData.hh"
#include <vector>

// Physical footprint: 200.0 mm wide x 80.00 mm tall, centred on
// the image's own centre (local origin = geometric centre of the logo).
std::vector<LogoGroup> BuildCUCEIBannerLogoData();

#endif
