// Auto-generated by gen_g4.py -- do not edit by hand.
#ifndef LIFILogoData_hh
#define LIFILogoData_hh

#include "LogoGeometryData.hh"
#include <vector>

// Physical footprint: 160.0 mm wide x 50.46 mm tall, centred on
// the image's own centre (local origin = geometric centre of the logo).
std::vector<LogoGroup> BuildLIFILogoData();

#endif
