// Auto-generated by gen_g4.py -- do not edit by hand.
// Shared data structures for logo geometry (LIFI / CUCEI) used by
// LogoGeometryBuilder to construct G4ExtrudedSolid volumes for the
// Geant4 visualizer.
#ifndef LogoGeometryData_hh
#define LogoGeometryData_hh

#include <vector>
#include "globals.hh"
#include "G4TwoVector.hh"
#include "G4Colour.hh"

struct LogoPolygon
{
  std::vector<G4TwoVector> outer;                 // outer boundary (CCW or CW, simple polygon)
  std::vector<std::vector<G4TwoVector>> holes;    // direct holes cut out of 'outer'
};

struct LogoGroup
{
  G4String name;
  G4Colour colour;
  std::vector<LogoPolygon> shapes;
};

#endif
