// Auto-generated by gen_g4.py -- do not edit by hand.
#ifndef LogoGeometryBuilder_hh
#define LogoGeometryBuilder_hh

#include "LogoGeometryData.hh"
#include "G4ThreeVector.hh"

class G4LogicalVolume;
class G4Material;

// Builds one Geant4 assembly of extruded solids for a single logo (a list
// of colour groups, each with one or more shapes potentially containing
// holes) and places every resulting volume inside 'motherLV' at 'position'.
//
//   groups          - logo data, e.g. from BuildLIFILogoData()
//   halfThicknessMm  - half-thickness (mm) of the extruded plaque
//   material        - material to assign to every logical volume
//   motherLV        - logical volume the logo is placed into
//   position        - placement of the logo's local origin (its image
//                     centre, AFTER scaling) inside the mother volume
//   checkOverlaps   - forwarded to G4PVPlacement
//   copyNoStart     - starting copy number, incremented per placed volume
//   scale           - uniform 2D scale factor applied to every polygon (and
//                     every hole) about the logo's own local origin (its
//                     image centre), via G4ExtrudedSolid's own scale1/scale2
//                     parameters -- e.g. 0.4 for 40% size. Holes are scaled
//                     by the SAME factor so letter cut-outs stay aligned
//                     with the (now smaller) outer boundary. Does NOT scale
//                     halfThicknessMm (the plaque stays equally thin).
//                     Default 1.0 = original size (trailing param, so
//                     existing positional call sites are unaffected).
//
// Returns the number of physical volumes created.
int BuildLogoGeometry(const std::vector<LogoGroup>& groups,
                      G4double halfThicknessMm,
                      G4Material* material,
                      G4LogicalVolume* motherLV,
                      const G4ThreeVector& position,
                      G4bool checkOverlaps = false,
                      G4int copyNoStart = 0,
                      G4double scale = 1.0);

#endif
