#!/usr/bin/env python3
# ============================================================================
# generate_energy_scan.py — single source of truth for the energy sweep.
#
# From one energy grid (by default the NIST PSTAR preferred-number grid read
# from ../../nist_data/energy_grid.csv, for direct cross-validation against
# PSTAR) this script generates BOTH sweep mechanisms, so they can never drift
# apart:
#
#   1) run_scan/run_<E>MeV.mac — one archivable macro per curve point
#      (data <-> conditions traceability, design section 7.2).
#   2) energy_scan.mac + run_point.mac (written next to this script) — the
#      /control/foreach variant, with the SAME energy list injected into the
#      foreach line and the SAME common conditions.
#
# Usage:
#   python3 generate_energy_scan.py            # NIST PSTAR grid
#   python3 generate_energy_scan.py --log 20   # 20 log points in [E_MIN, E_MAX]
#
# Then either:
#   for m in run_scan/run_*MeV.mac; do ./slab "$m"; done
# or:
#   ./slab macros/energy_scan.mac
# ============================================================================
import argparse
import math
import pathlib
import pandas as pd

# --- Common sweep conditions (edit here, not in the macros) -----------------
MATERIAL = "G4_WATER"
THICKNESS = "5 mm"
SIZE_XY = "10 cm"
N_LAYERS = 50
CUT = "0.01 mm"
CUT_TAG = "cut1mm"   # appears in the data file name
N_EVENTS = 1000     # test, raise for production
"""
Energy grid: preferred-number array, same as NIST PSTAR data
in the range of 1 KeV-1000 MeV for visualization purposes only.
Identical to ../../nist_data/energy_grid.csv,
for direct cross-validation.
"""

NIST_GRID_CSV = pathlib.Path("../../nist_data/energy_grid.csv")
E_MIN, E_MAX = 3, 1000.0  # range for --log

#   Output locations: per-point macros go to run_scan/; the foreach pair is
#   rewritten in place, next to this script, this is, the macros/ directory.
OUT_DIR = pathlib.Path("run_scan")
MACRO_DIR = pathlib.Path(__file__).resolve().parent

# Path of run_point.mac as seen from where ./slab is executed (build dir).
RUN_POINT_INVOCATION_PATH = "macros/run_point.mac"

POINT_TEMPLATE = """# Macro generated by generate_energy_scan.py — do NOT edit by hand.
# Sweep point: {energy:g} MeV, cut {cut} ({cut_tag})
/control/verbose 0
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/absorber/material {material}
/absorber/thickness {thickness}
/absorber/sizeXY {size_xy}
/absorber/numberOfLayers {n_layers}

/physics/absorberCut {cut}

/run/initialize

/gun/particle proton
/gun/energy {energy:g} MeV

/analysis/setFileName dedx_{energy:g}MeV_{cut_tag}

/run/beamOn {n_events}
"""
ENERGY_SCAN_TEMPLATE = """# ============================================================================
# energy_scan.mac — energy sweep for the dE/dx vs E curve
# GENERATED by generate_energy_scan.py — do NOT edit by hand; edit the
# constants (and/or the NIST grid CSV) in that script and re-run it.
# Usage: ./slab macros/energy_scan.mac
#
# Energy grid: {grid_description} ({n_points} points).
# Conditions COMMON to every point are fixed here, once; the energy and the
# output file name per point are set by run_point.mac through the {{energy}}
# alias.
# ============================================================================
/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# --- Common conditions --------------------------------------------------
/absorber/material {material}
/absorber/thickness {thickness}
/absorber/sizeXY {size_xy}
/absorber/numberOfLayers {n_layers}

/physics/absorberCut {cut}
/control/alias cutTag {cut_tag}
/control/alias nEvents {n_events}

/run/initialize

/gun/particle proton

# --- Sweep: one run per energy (design, section 3.2) --------------------
/control/foreach {run_point_path} energy "{energy_list}"
"""

# NOTE: this template is written verbatim (no str.format), so the Geant4
# alias braces {energy}, {cutTag}, {nEvents} are literal single braces.
RUN_POINT_TEMPLATE = """# ============================================================================
# run_point.mac — one point of the energy sweep.
# GENERATED by generate_energy_scan.py — do NOT edit by hand.
# Do NOT run directly: it is invoked by energy_scan.mac via /control/foreach,
# which defines the {energy} alias (in MeV). The {cutTag} and {nEvents}
# aliases also come from energy_scan.mac.
# ============================================================================
/gun/energy {energy} MeV
/analysis/setFileName dedx_{energy}MeV_{cutTag}
/run/beamOn {nEvents}
"""

def load_energies(log_points:int) -> tuple[list[float], str]:
    """Return the energy list (MeV) and a short description of its origin,
    reminding that it's the same as the one generated by NIST PSTAR."""
    if log_points > 1:
        step = (math.log10(E_MAX) - math.log10(E_MIN)) / (log_points - 1)
        energies = [round(10 ** (math.log10(E_MIN) + i * step, 1), 1)
                    for i in range(log_points)]
        return energies, f"logarithmic, [min: {E_MIN:g}, max: {E_MAX:g}] MeV"
    if not NIST_GRID_CSV.is_file():
        raise SystemExit(
            f"error: {NIST_GRID_CSV} not found, run from the directory where"
            f"the defined relative path is valid, or use --log N")
    energies = (pd.read_csv(NIST_GRID_CSV, sep=",", header=0)
                .iloc[:, 0].astype(float).to_list())
    return energies, f"NIST PSTAR grid from {NIST_GRID_CSV}"

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--log", type=int, metavar="N", default=0,
        help="use N logarithmically spaced points between "
             f"{E_MIN:g} and {E_MAX:g} MeV instead of the NIST grid")
    args = parser.parse_args()

    energies, grid_description = load_energies(args.log)
    # --- 1) One archivable macro per sweep point ----------------------------
    OUT_DIR.mkdir(exist_ok=True)
    for e in energies:
        macro = POINT_TEMPLATE.format(
            energy=e, material=MATERIAL, thickness=THICKNESS,
            size_xy=SIZE_XY, n_layers=N_LAYERS, cut=CUT,
            cut_tag=CUT_TAG, n_events=N_EVENTS)
        path = OUT_DIR / f"run_{e:g}MeV.mac"
        path.write_text(macro)
    print(f"wrote {len(energies)} macros in {OUT_DIR}/")

    # --- 2) Keep the foreach pair in sync with the same grid ----------------
    # %g formatting must match POINT_TEMPLATE so the {energy} alias produces
    # identical file names in both mechanisms.
    energy_list = " ".join(f"{e:g}" for e in energies)
    scan_path = MACRO_DIR / "energy_scan.mac"
    scan_path.write_text(ENERGY_SCAN_TEMPLATE.format(
        grid_description=grid_description, n_points=len(energies),
        material=MATERIAL, thickness=THICKNESS, size_xy=SIZE_XY,
        n_layers=N_LAYERS, cut=CUT, cut_tag=CUT_TAG, n_events=N_EVENTS,
        run_point_path=RUN_POINT_INVOCATION_PATH, energy_list=energy_list))
    print(f"wrote {scan_path} ({len(energies)} points, {grid_description})")

    point_path = MACRO_DIR / "run_point.mac"
    point_path.write_text(RUN_POINT_TEMPLATE)
    print(f"wrote {point_path}")

    print("\nRun the sweep with either:")
    print(f'  for m in {OUT_DIR}/run_*MeV.mac; do ./slab "$m"; done')
    print("  ./slab macros/energy_scan.mac")
    print("\nNOTE: if you build out-of-source, re-run cmake (or copy the "
          "regenerated macros) so the build dir picks up the new "
          "energy_scan.mac / run_point.mac.")


if __name__ == "__main__":
    main()
