#!/usr/bin/env python3
# ============================================================================
# generate_energy_scan.py — generates a family of run_<E>MeV.mac macros from
# a template, as an alternative to energy_scan.mac (/control/foreach) when an
# archivable macro per curve point is wanted (data <-> conditions
# traceability, design section 7.2), or when a different energy spacing
# (e.g. logarithmic) is needed without hand-editing macros.
#
# Usage:
#   python3 generate_energy_scan.py            # default energies
#   python3 generate_energy_scan.py --log 20   # 20 log points between E_MIN and E_MAX
#
# Then:  for m in run_scan/run_*MeV.mac; do ./slab "$m"; done
# ============================================================================
import argparse
import math
import pathlib

# --- Common sweep conditions (edit here, not in the macros) -----------------
MATERIAL = "G4_WATER"
THICKNESS = "5 mm"
SIZE_XY = "10 cm"
N_LAYERS = 50
CUT = "1 mm"
CUT_TAG = "cut1mm"   # appears in the data file name
N_EVENTS = 100000
ENERGIES_MEV = [50, 70, 100, 150, 200, 250, 500, 1000]  # design default
E_MIN, E_MAX = 30.0, 1000.0  # range for --log
OUT_DIR = pathlib.Path("run_scan")

TEMPLATE = """# Macro generated by generate_energy_scan.py — do NOT edit by hand.
# Sweep point: {energy:g} MeV, cut {cut} ({cut_tag})
/control/verbose 0
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/absorber/material {material}
/absorber/thickness {thickness}
/absorber/sizeXY {size_xy}
/absorber/numberOfLayers {n_layers}

/physics/absorberCut {cut}

/run/initialize

/gun/particle proton
/gun/energy {energy:g} MeV

/analysis/setFileName dedx_{energy:g}MeV_{cut_tag}

/run/beamOn {n_events}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--log", type=int, metavar="N", default=0,
        help="use N logarithmically spaced points between "
             f"{E_MIN:g} and {E_MAX:g} MeV instead of the default list")
    args = parser.parse_args()

    if args.log > 1:
        step = (math.log10(E_MAX) - math.log10(E_MIN)) / (args.log - 1)
        energies = [round(10 ** (math.log10(E_MIN) + i * step), 1)
                    for i in range(args.log)]
    else:
        energies = ENERGIES_MEV

    OUT_DIR.mkdir(exist_ok=True)
    for e in energies:
        macro = TEMPLATE.format(
            energy=e, material=MATERIAL, thickness=THICKNESS,
            size_xy=SIZE_XY, n_layers=N_LAYERS, cut=CUT,
            cut_tag=CUT_TAG, n_events=N_EVENTS)
        path = OUT_DIR / f"run_{e:g}MeV.mac"
        path.write_text(macro)
        print(f"wrote {path}")

    print(f"\n{len(energies)} macros in {OUT_DIR}/ — run them with:")
    print(f'  for m in {OUT_DIR}/run_*MeV.mac; do ./slab "$m"; done')


if __name__ == "__main__":
    main()
