#!/usr/bin/env python3
# ============================================================================
# generate_energy_scan.py — single source of truth for the energy sweep.
#
# From one energy grid (by default the NIST PSTAR preferred-number grid read
# from ../../nist_data/energy_grid.csv, for direct cross-validation against
# PSTAR) this script generates BOTH sweep mechanisms, so they can never drift
# apart:
#
#   1) run_scan/run_<Etag>MeV.mac — one archivable macro per curve point
#      (data <-> conditions traceability, design section 7.2).
#   2) energy_scan.mac (written next to this script) — a single macro with
#      the per-point commands INLINED (no /control/foreach: see note below).
#
# FILE-NAME TAGS: G4AnalysisManager treats everything after the last '.' in
# the file name as a file-type extension, so decimal energies like 0.001
# would mangle the output names (e.g. "dedx_0.001MeV_..." loses everything
# after "0"). Energies are therefore encoded in file names with 'p' instead
# of the decimal point: 0.001 MeV -> "dedx_0p001MeV_cut1mm". The /gun/energy
# command keeps the true numeric value.
#
# WHY NO foreach ANYMORE: /control/foreach passes a single alias, but each
# point now needs two representations of the energy (numeric for /gun/energy,
# 'p'-tag for /analysis/setFileName) and Geant4 macros cannot do string
# substitution. Since energy_scan.mac is generated anyway, the points are
# simply written out inline. run_point.mac is kept only as a deprecated stub
# so that existing CMakeLists.txt configure_file() rules do not break.
#
# Usage:
#   python3 generate_energy_scan.py            # NIST PSTAR grid
#   python3 generate_energy_scan.py --log 20   # 20 log points in [E_MIN, E_MAX]
#
# Then either:
#   for m in run_scan/run_*MeV.mac; do ./slab "$m"; done
# or:
#   ./slab macros/energy_scan.mac
# ============================================================================
import argparse
import math
import pathlib
import pandas as pd

# --- Common sweep conditions (edit here, not in the macros) -----------------
MATERIAL = "G4_WATER"
THICKNESS = "5 mm"
SIZE_XY = "10 cm"
N_LAYERS = 50
CUT = "1 mm"
CUT_TAG = "cut1mm"   # appears in the data file name
N_EVENTS = 1000      # test statistics; raise for production

# Energy grid: preferred-number array, same as NIST PSTAR data in the range
# 1 keV - 10 GeV, for direct cross-validation. Identical to
# ../../nist_data/energy_grid.csv.
NIST_GRID_CSV = pathlib.Path("../../nist_data/energy_grid.csv")
E_MIN, E_MAX = 3.0, 1000.0  # range for --log

# Output locations: per-point macros go to run_scan/; energy_scan.mac and
# the run_point.mac stub are rewritten in place, next to this script.
OUT_DIR = pathlib.Path("run_scan")
MACRO_DIR = pathlib.Path(__file__).resolve().parent


def etag(e: float) -> str:
    """Energy tag for file names: %g formatting with '.' -> 'p'.

    G4AnalysisManager interprets the text after the last '.' as a file
    extension, so 0.001 must become '0p001' in any /analysis/setFileName.
    """
    return f"{e:g}".replace(".", "p")


POINT_TEMPLATE = """# Macro generated by generate_energy_scan.py — do NOT edit by hand.
# Sweep point: {energy:g} MeV, cut {cut} ({cut_tag})
/control/verbose 0
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/absorber/material {material}
/absorber/thickness {thickness}
/absorber/sizeXY {size_xy}
/absorber/numberOfLayers {n_layers}

/physics/absorberCut {cut}

/run/initialize

/gun/particle proton
/gun/energy {energy:g} MeV

/analysis/setFileName dedx_{tag}MeV_{cut_tag}

/run/beamOn {n_events}
"""

ENERGY_SCAN_HEADER = """# ============================================================================
# energy_scan.mac — energy sweep for the dE/dx vs E curve
# GENERATED by generate_energy_scan.py — do NOT edit by hand; edit the
# constants (and/or the NIST grid CSV) in that script and re-run it.
# Usage: ./slab macros/energy_scan.mac
#
# Energy grid: {grid_description} ({n_points} points).
# Points are inlined (no /control/foreach) because file names need the
# 'p'-encoded energy tag (0.001 -> 0p001) while /gun/energy needs the
# numeric value, and a foreach alias cannot provide both.
# ============================================================================
/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# --- Common conditions --------------------------------------------------
/absorber/material {material}
/absorber/thickness {thickness}
/absorber/sizeXY {size_xy}
/absorber/numberOfLayers {n_layers}

/physics/absorberCut {cut}

/run/initialize

/gun/particle proton

# --- Sweep: one run per energy (design, section 3.2) --------------------
"""

ENERGY_SCAN_POINT = """
# --- {energy:g} MeV
/gun/energy {energy:g} MeV
/analysis/setFileName dedx_{tag}MeV_{cut_tag}
/run/beamOn {n_events}
"""

RUN_POINT_STUB = """# ============================================================================
# run_point.mac — DEPRECATED stub, kept only so CMake's configure_file()
# rule for this path keeps working. The energy sweep no longer uses
# /control/foreach: energy_scan.mac (generated by generate_energy_scan.py)
# inlines every point, because file names need the 'p'-encoded energy tag
# (0.001 -> 0p001) while /gun/energy needs the numeric value, and a foreach
# alias cannot provide both. Safe to delete once the CMakeLists.txt entry
# for macros/run_point.mac is removed.
# ============================================================================
"""


def load_energies(log_points: int) -> tuple[list[float], str]:
    """Return the energy list (MeV) and a short description of its origin."""
    if log_points > 1:
        step = (math.log10(E_MAX) - math.log10(E_MIN)) / (log_points - 1)
        energies = [round(10 ** (math.log10(E_MIN) + i * step), 1)
                    for i in range(log_points)]
        return energies, f"logarithmic, [{E_MIN:g}, {E_MAX:g}] MeV"
    if not NIST_GRID_CSV.is_file():
        raise SystemExit(
            f"error: {NIST_GRID_CSV} not found — run from the directory where "
            "that relative path is valid, or use --log N")
    energies = (pd.read_csv(NIST_GRID_CSV, sep=",", header=0)
                .iloc[:, 0].dropna().astype(float).to_list())
    return energies, f"NIST PSTAR grid from {NIST_GRID_CSV}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--log", type=int, metavar="N", default=0,
        help="use N logarithmically spaced points between "
             f"{E_MIN:g} and {E_MAX:g} MeV instead of the NIST grid")
    args = parser.parse_args()

    energies, grid_description = load_energies(args.log)

    # Guard against tag collisions (two grid values mapping to one file name).
    tags = [etag(e) for e in energies]
    if len(set(tags)) != len(tags):
        dupes = sorted({t for t in tags if tags.count(t) > 1})
        raise SystemExit(f"error: duplicate energy tags in the grid: {dupes}")

    # --- 1) One archivable macro per sweep point ----------------------------
    OUT_DIR.mkdir(exist_ok=True)
    for e in energies:
        macro = POINT_TEMPLATE.format(
            energy=e, tag=etag(e), material=MATERIAL, thickness=THICKNESS,
            size_xy=SIZE_XY, n_layers=N_LAYERS, cut=CUT,
            cut_tag=CUT_TAG, n_events=N_EVENTS)
        path = OUT_DIR / f"run_{etag(e)}MeV.mac"
        path.write_text(macro)
    print(f"wrote {len(energies)} macros in {OUT_DIR}/")

    # --- 2) energy_scan.mac with the same grid, points inlined --------------
    scan = ENERGY_SCAN_HEADER.format(
        grid_description=grid_description, n_points=len(energies),
        material=MATERIAL, thickness=THICKNESS, size_xy=SIZE_XY,
        n_layers=N_LAYERS, cut=CUT)
    for e in energies:
        scan += ENERGY_SCAN_POINT.format(
            energy=e, tag=etag(e), cut_tag=CUT_TAG, n_events=N_EVENTS)
    scan_path = MACRO_DIR / "energy_scan.mac"
    scan_path.write_text(scan)
    print(f"wrote {scan_path} ({len(energies)} points, {grid_description})")

    # --- 3) Deprecated run_point.mac stub (CMake compatibility) -------------
    point_path = MACRO_DIR / "run_point.mac"
    point_path.write_text(RUN_POINT_STUB)
    print(f"wrote {point_path} (deprecated stub)")

    print("\nRun the sweep with either:")
    print(f'  for m in {OUT_DIR}/run_*MeV.mac; do ./slab "$m"; done')
    print("  ./slab macros/energy_scan.mac")
    print("\nNOTE: if you build out-of-source, re-run cmake (or copy the "
          "regenerated macros) so the build dir picks up the new "
          "energy_scan.mac.")


if __name__ == "__main__":
    main()